#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'ros-tcp-endpoint==0.0.1','console_scripts','default_server_endpoint'
__requires__ = 'ros-tcp-endpoint==0.0.1'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('ros-tcp-endpoint==0.0.1', 'console_scripts', 'default_server_endpoint')()
    )
